# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)


user1 = User.create!(user_name: "Jon", email: "J@yahoo.com", password: "password")
user2 = User.create!(user_name: "Bill", email: "B@aol.com", password: "password")
user3 = User.create!(user_name: "Kate", email: "K@aol.com", password: "password")
user4 = User.create!(user_name: "Jess", email: "J@gmail.com", password: "password")

campaign1 = Campaign.create!(name: "Alpha Squad", description: "All the biggest badasses from the Fellowship", dm: user1)
campaign2 = Campaign.create!(name: "Omega Squad", description: "Here are some other guys you may like", dm: user1)
campaign3 = Campaign.create!(name: "Hobbit Time", description: "Chilling with the little dudes", dm: user4)

pc1 = Pc.create!(user: user2, name: "Galadriel", campaign: campaign1, avatar: "https://s3.amazonaws.com/dmscreen/pcs/enchntress.jpg")
pc2 = Pc.create!(user: user3, name: "Aragorn", campaign: campaign1, avatar: "https://s3.amazonaws.com/dmscreen/pcs/arragorn.jpg")
pc3 = Pc.create!(user: user4, name: "Gandalph", campaign: campaign1, avatar: "https://s3.amazonaws.com/dmscreen/pcs/Gandalf.jpg")
pc4 = Pc.create!(user: user2, name: "Gimli", campaign: campaign2, avatar: "https://s3.amazonaws.com/dmscreen/pcs/Gimli.jpg")
pc5 = Pc.create!(user: user3, name: "Legolas", campaign: campaign2, avatar: "https://s3.amazonaws.com/dmscreen/pcs/Legolas.png")
pc6 = Pc.create!(user: user4, name: "Boromir", campaign: campaign2, avatar: "https://s3.amazonaws.com/dmscreen/pcs/boromir.jpg")
pc7 = Pc.create!(user: user1, name: "Frodo", campaign: campaign3, avatar: "https://s3.amazonaws.com/dmscreen/pcs/Frodo.jpg")
pc8 = Pc.create!(user: user2, name: "Merry", campaign: campaign3, avatar: "https://s3.amazonaws.com/dmscreen/pcs/Merry.jpg")
pc9 = Pc.create!(user: user3, name: "Pippin", campaign: campaign3, avatar: "https://s3.amazonaws.com/dmscreen/pcs/pippin.jpg")

dungeon1 = Dungeon.create!(name: "The Forgotten Forge", description: "A dwarven forge, long forgotten, full Adventures.", cover_picture: "https://s3.amazonaws.com/dmscreen/Maps/Forge-of-Fury.jpg", master_floor_plan: "https://s3.amazonaws.com/dmscreen/Maps/FloorPlan-Forge.jpg" )
dungeon2 = Dungeon.create!(name: "The Sunless Citadelle", description: "A Citadelle, long forgotten, full of monsters.", cover_picture: "https://s3.amazonaws.com/dmscreen/Maps/sunless-citadel.jpg", master_floor_plan: "https://s3.amazonaws.com/dmscreen/Maps/FloorPlan-Forge.jpg" )

room1 = Room.create!(dungeon: dungeon1, picture:"https://s3.amazonaws.com/dmscreen/Maps/Forge-Room1.jpg", room_id: 1, description: "This is the 1st room")
room2 = Room.create!(dungeon: dungeon1, picture:"https://s3.amazonaws.com/dmscreen/Maps/Forge-Room2.jpg", room_id: 2, description: "This is the 2nd room", traps:"There's a trap here", monsters:"Theres a monster here")
room3 = Room.create!(dungeon: dungeon1, picture:"https://s3.amazonaws.com/dmscreen/Maps/Forge-Room3.jpg", room_id: 3, description: "This is the 3rd room", traps:"Another trap!", treasure:"Here be Treasure!")
room4 = Room.create!(dungeon: dungeon1, picture:"https://s3.amazonaws.com/dmscreen/Maps/Forge-room4.png", room_id: 4, description: "This is the 4th room", traps:"Another trap!", treasure:"Here be Treasure!")
room5 = Room.create!(dungeon: dungeon1, picture:"https://s3.amazonaws.com/dmscreen/Maps/Forge-room5.jpg", room_id: 5, description: "Another room")
room6 = Room.create!(dungeon: dungeon1, picture:"https://s3.amazonaws.com/dmscreen/Maps/Forge-Room6.jpg", room_id: 6, description: "I have lost my passion for describing rooms")
room7 = Room.create!(dungeon: dungeon1, picture:"https://s3.amazonaws.com/dmscreen/Maps/Forge-room7.jpg", room_id: 7, description: "I have lost my passion for describing rooms")
room8 = Room.create!(dungeon: dungeon1, picture:"https://s3.amazonaws.com/dmscreen/Maps/Forge-room8.png", room_id: 8, description: "I have lost my passion for describing rooms")
room9 = Room.create!(dungeon: dungeon1, picture:"https://s3.amazonaws.com/dmscreen/Maps/Forge-Room9.jpg", room_id: 9, description: "I have lost my passion for describing rooms")
room10 = Room.create!(dungeon: dungeon1, picture:"https://s3.amazonaws.com/dmscreen/Maps/Forge-Room10.png", room_id: 10, description: "I have lost my passion for describing rooms")
room11= Room.create!(dungeon: dungeon1, picture:"https://s3.amazonaws.com/dmscreen/Maps/Forge-room11.jpg", room_id: 11, description: "I have lost my passion for describing rooms")
room12 = Room.create!(dungeon: dungeon1, picture:"https://s3.amazonaws.com/dmscreen/Maps/Forge-room12.jpg", room_id: 12, description: "I have lost my passion for describing rooms")
room13 = Room.create!(dungeon: dungeon1, picture:"https://s3.amazonaws.com/dmscreen/Maps/Forge-Room13.jpg", room_id: 13, description: "I have lost my passion for describing rooms", treasure: "All the best treasure and a Kit-Kat Bar")
room14 = Room.create!(dungeon: dungeon1, picture:"https://s3.amazonaws.com/dmscreen/Maps/Forge-Room14.jpg", room_id: 14, description: "I have lost my passion for describing rooms")
room15 = Room.create!(dungeon: dungeon2, room_id: 1, description: "This is the other 1st room", monsters:"Ugly Monsters! Woof.")
room16 = Room.create!(dungeon: dungeon2, room_id: 2, description: "This is the other 2nd room", traps:"There's a trap here", monsters:"Theres a monster here", treasure:"Here be Treasure!")

abutter1 = Abutter.create!(ingress: room1, egress: room2)
abutter2 = Abutter.create!(ingress: room2, egress: room1)
abutter3 = Abutter.create!(ingress: room2, egress: room3)
abutter4 = Abutter.create!(ingress: room3, egress: room2)
abutter5 = Abutter.create!(ingress: room3, egress: room5)
abutter6 = Abutter.create!(ingress: room5, egress: room3)
abutter7 = Abutter.create!(ingress: room3, egress: room4)
abutter8 = Abutter.create!(ingress: room4, egress: room3)
abutter9 = Abutter.create!(ingress: room4, egress: room14)
abutter10 = Abutter.create!(ingress: room14, egress: room4)
abutter11 = Abutter.create!(ingress: room5, egress: room6)
abutter12 = Abutter.create!(ingress: room6, egress: room5)
abutter13 = Abutter.create!(ingress: room5, egress: room7)
abutter14 = Abutter.create!(ingress: room7, egress: room5)
abutter15 = Abutter.create!(ingress: room5, egress: room8)
abutter16 = Abutter.create!(ingress: room8, egress: room5)
abutter17 = Abutter.create!(ingress: room8, egress: room9)
abutter18 = Abutter.create!(ingress: room9, egress: room8)
abutter19 = Abutter.create!(ingress: room8, egress: room11)
abutter20 = Abutter.create!(ingress: room11, egress: room8)
abutter21 = Abutter.create!(ingress: room8, egress: room12)
abutter22 = Abutter.create!(ingress: room12, egress: room8)
abutter23 = Abutter.create!(ingress: room8, egress: room13)
abutter24 = Abutter.create!(ingress: room13, egress: room8)
abutter25 = Abutter.create!(ingress: room13, egress: room14)
abutter26 = Abutter.create!(ingress: room14, egress: room13)
abutter27 = Abutter.create!(ingress: room8, egress: room10)
abutter28 = Abutter.create!(ingress: room10, egress: room8)
abutter29 = Abutter.create!(ingress: room10, egress: room9)
abutter30 = Abutter.create!(ingress: room9, egress: room10)

dc1 = DungeonCampaign.create!(campaign: campaign1, dungeon: dungeon1)
dc2 = DungeonCampaign.create!(campaign: campaign2, dungeon: dungeon1)
dc3 = DungeonCampaign.create!(campaign: campaign3, dungeon: dungeon2)
